config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  root 'static_pages#home'

  get 'help' => 'static_pages#help'
  get 'about' => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'signup'  => 'users#new'

  resources :users
  resources :account_activations, only: [:edit]

  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :remember_token, :activation_token
  before_save :downcase_email
  before_create :create_activation_digest
  before_save { self.email = email.downcase }
  validates :name, presence: true, length: { maximum: 50 }

  #VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  #ドットが２つ続くかどうかの正規表現
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }

  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
  # 渡された文字列のハッシュ値を返す
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  #永続セッションのためにユーザーをデータベースに記憶する
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest,User.digest(remember_token))
  end

  #渡された文字列のハッシュ値を返す
  #class <<self
  #と記述していれば、以下のself.digest, self.new_tokenのselfは省略できる。selfはUserクラスであるので。
  def self.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
    BCrypt::Password.create(string,cost: cost)
  end

  #ランダムなトークンを返す
  def self.new_token
    SecureRandom.urlsafe_base64
  end

  #渡されたトークンがダイジェストと一致したらtrueを返す
  #記憶ダイジェストがnilの場合はfalseを返す
  def authenticated?(attribute,token)
    digest = send("#{attribute}_digest")
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end

  #ユーザーのログイン情報を破棄する
  def forget
    update_attribute(:remember_digest, nil)
  end

  def activate
    update_columns(activated: FILL_IN,activated_at: FILL_IN)
  end

  def send_activation_email
    UserMailer.account_activation(self).deliver_now
  end

  private
    #メールアドレスを全て小文字にする
    def downcase_email
      self.email = email.downcase
    end

    def create_activation_digest
      self.activation_token = User.new_token
      self.activation_digest = User.digest(activation_token)
    end
end

app/controllers/account_activations_controller.rb
class AccountActivationsController < ApplicationController

  def edit
    user = User.find_by(email: params[:email])
    if user && !user.activated? && user.authenticated?(:activation, params[:id])
      user.activate
      log_in user
      flash[:success] = "Account activated!"
      redirect_to user
    else
      flash[:danger] = "invalid activation link"
      redirect_to root_url
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/sessions_controller.rb
include SessionsHelper
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email:params[:session][:email.downcase])
    if user && user.authenticate(params[:session][:password])
      if user.activated?
        log_in user
        params[:session][:remember_me] == '1' ? remember(user) : forget(user)
        redirect_back_or user
      else
        message = "Account not activated"
        message += "Check your email for the activation link"
        flash[:warning] = message
        redirect_to root_url
      end
    else
      flash.now[:danger] = 'Invalid email/password combination' # 本当は正しくない
      render 'new'

    end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_url
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/controllers/users_controller.rb
include SessionsHelper
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:index, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update]
  before_action :admin_user, only: :destroy

  def new
    @user = User.new
  end

  def index
    @users = User.paginate(page: params[:page])
  end

  def show
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)
    if @user.save
      @user.send_activation_email
      flash[:info] = "Please check your email account!"
      redirect_to root_url
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted..."
    redirect_to users_url
  end

  def logged_in_user
    unless logged_in?
      store_location
      flash[:danger] = "Please log in."
      redirect_to login_url
    end
  end

  private

   def user_params
     params.require(:user).permit(:name, :email, :password,
                                  :password_confirmation)
   end

   def correct_user
     @user = User.find(params[:id])
     redirect_to(root_url) unless current_user?(@user)
   end

   #管理者かどうか確認
   def admin_user
     redirect_to(root_url) unless current_user.admin?
   end

end

app/helpers/account_activations_helper.rb
module AccountActivationsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def full_title(page_title = '') #タイトルを引数に取る
    base_title = "Ruby on Rails Tutorial Sample App" #ベースタイトル
    if page_title.empty?                        #ページタイトルが空かどうか？
      base_title                                #空ならばベースタイトルだけを表示
    else
      page_title + "| " + base_title           #ページタイトルと一緒にベースタイトルを表
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  # 渡されたユーザーでログインする
  def log_in(user)
    session[:user_id] = user.id
  end

  #ユーザーを永続的セッションに記憶する
  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  #渡されたユーザーがログイン済みであればtrueを返す
  def current_user?(user)
    user == current_user
  end

  # 現在ログイン中のユーザーを返す (いる場合)
  # user_idにuser_idのセッションを代入した結果、ユーザーIDのセッションが存在すれば・・・で場合分け
  def current_user
    if(user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif(user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user && user.authenticated?(:remember, cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end

  # ユーザーがログインしていればtrue、その他ならfalseを返す
  def logged_in?
    !current_user.nil?
  end

  #永続的セッションを破棄
  def forget(user)
    user.forget
    session.delete(:user_id)
    session.delete(:remember_token)
    @current_user = nil
  end

  #現在のユーザーをログアウトする
  def log_out
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end

  #記憶したurl(もしくはデフォルト値)にリダイレクト
  def redirect_back_or(default)
    redirect_to(session[:forwading_url] || default)
    session.delete(:forwading_url)
  end

  #アクセスしようとしたurlを覚えておく
  def store_location
    session[:forwading_url] = request.original_url if request.get?
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper

  # 引数で与えられたユーザーのGravatar画像を返す
  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end

end

app/views/layouts/_footer.html.slim
footer
  small 
    | The
    a<> href="http://www.railstutorial.org/" Ruby on Rails Tutorial
    | by
    a<> href="http://www.michaelhartl.com/" Michael Hartl

  nav
    ul
      li 
        = link_to "About", about_path
      li 
        = link_to "Contact", contact_path
      li 
        a<> href="http://news.railstutorial.org/" News

app/views/layouts/_header.html.slim
header class=["navbar navbar-fixed-top navbar-inverse"]
  .container
    = link_to "sample app", '#', id:"logo"
    nav
      ul class=["nav navbar-nav navbar-right"]
        li = link_to "Home", root_path
        li = link_to "Help", help_path
        - if logged_in?
          li = link_to "Users", users_path
          li class="dropdown"
            a<> href="#" class="dropdown-toggle" data-toggle="dropdown" Account
            b<> class="carat"
            ul class="dropdown-menu"
              li 
                = link_to "Profile", current_user
                = link_to "Settings", edit_user_path(current_user)
              li 
                = link_to "Settings", '#'
              li class="divider"
              li
                = link_to "Log out", logout_path, method: "delete"
        - else
          li
            = link_to "Log in", login_path
             

app/views/layouts/_shim.html.slim
<!--[if lt IE 9]>
  script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js"
  
<![endif]-->

app/views/layouts/application.html.slim
doctype html
html
  head
    meta charset="utf-8"
    meta http-equiv="X-UA-Compatible" content="IE=edge"

    title
      = full_title(yield(:title)) 
    /! HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries
    /[if lt IE 9]
      = javascript_include_tag "https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js", "https://oss.maxcdn.com/respond/1.4.2/respond.min.js"
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
    = render 'layouts/shim' 
  body
    = render 'layouts/header'
    .container
      - flash.each do |message_type, message|
        div.alert class="alert-#{message_type}"
        = message
      = yield
      = render 'layouts/footer'
      = debug(params) 
       -if Rails.env.development?
      

app/views/shared/_error_messages.html.slim
- if @user.errors.any?
  .error_explanation
    alert.alert-danger
      | The form contains
      = pluralize(@user.errors.count, "error")
    
    ul
      - @user.errors.full_messages.each do |msg|
        li 
          = msg

app/views/static_pages/about.html.slim
- provide(:title, "About")

body
  h1 About

  p
    a<> href="http://railstutoeial.jp"
      em<> Ruby on Rails Tutorial
    | is a 
    a<> href="http://railstutorial.jp/book" book
    | and
    a<> href="http://screencasts.railstutorial.org/" screencast series
    | to teach web development with
    a<> href="http://rubyonrails.org" Ruby on Rails
    | This is the sample application for the tutorial.
 

app/views/static_pages/contact.html.slim
- provide(:title, "Contact")

h1 Contact
p 
  Contact the Ruby on Rails Tutorial about the sample app at the
  a<> href="http://www.railstutorial.org/#contact" contact page

app/views/static_pages/help.html.slim
- provide(:title, "Help")

body
  h1 Help
  p 
    | Get help on the Ruby on Rails Tutorial at the
    a<> href="http://railstutorial.jp/help" Rails Tutorial help 
    | Page To get help on this sample app, see the
    a<> href="heep://railstutorial.jp/book" 
      em Ruby on Rails Tutorial book

app/views/static_pages/home.html.slim
- provide(:title, "Home")

body
  p 
  | This is the home page for the 
  a> href = "http://railstutorial.jp" Ruby on Rails Tutorial sample application

  .jumbotron.center
    .container
        h1 Welcome to the Sample App

        h2 This is the home page for the
        a<> href = "http://www.railstutorial.org/" Ruby on Rails Tutorial
        | sample application 
    = link_to "Sign up now!", signup_path, class:"btn btn-lg btn-primary"

  = link_to root_path do
    == image_tag "rails.png", :alt => "Rails logo" 
    
    

app/views/users/_form.html.slim
= form_for(@user) do |f|
  = render 'shared/error_messages', object: @user
  
  = f.label :name
  = f.text_field :name, class: 'form-control'
  
  = f.label :email
  = f.email_field :email, class: 'form-control'
  
  = f.label :password
  = f.password_field :password, class: 'form-control'
  
  = f.label :password_confirmation, "confirmation"
  = f.password_field :password_confirmation, class: 'form-control'
  
  = f.submit yield(:button_text), class: "btn btn-primary"

app/views/users/_user.html.slim
li 
  = gravatar_for user, size: 50
  = link_to user.name, user
  - if current_user.admin? && !current_user?(user)
    = link_to "delete", user, method: :delete, class:"btn", data: { confirm: "You sure? "}

app/views/users/edit.html.slim
- provide(:title, "Edit user")
- provide(:button_text, 'Save changes')
h1 Update your profile

.row
  col-md-6.col-md-offset-3
    = render 'form'
    .gravatat_edit
      = gravatar_for @user
      a<> href="http://gravatar.com/emails" target="_blank" change

app/views/users/index.html.slim
- provide(:title, 'All users')
h1 All users

= will_paginate

.users
  - @users.each do |user|
    = render user
= will_paginate

app/views/users/new.html.slim
- provide(:title, "Sign up")
- provide(:button_text, 'Create my account')

h1 SignUp

.row
  .col-md-6.colmd-offset-3
    = render 'form'

app/views/users/show.html.slim
- provide(:title, @user.name)

.row
  aside.col-md-4
    section.user_info
      h1
        = gravatar_for @user
        = @user.name
        